services:
  - type: web
    name: frontend
    env: docker
    repo: https://github.com/odoh-tc/Inventory_app
    branch: main
    dockerfilePath: frontend/Dockerfile
    envVars:
      - key: CHOKIDAR_USEPOLLING
        value: "true"
    healthCheckPath: /
    healthCheckPort: 3000
    healthCheckCommand: curl -f http://localhost:3000/ || exit 1

  - type: web
    name: api
    env: docker
    repo: https://github.com/odoh-tc/Inventory_app
    branch: main
    dockerfilePath: api/Dockerfile
    envVarsFromFiles:
      - path: api/.env
    healthCheckPath: /
    healthCheckPort: 8000
    healthCheckCommand: curl -f http://localhost:8000/ || exit 1
